// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuBz8RuBcMx5dfhwubWpuaAccCjLLIXoM',
    appId: '1:363823258532:web:4ed7ffe07dc66cd0deff31',
    messagingSenderId: '363823258532',
    projectId: 'quest-demo-12845',
    authDomain: 'quest-demo-12845.firebaseapp.com',
    storageBucket: 'quest-demo-12845.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxi_m7ssQZzNekay0MXfadM412Z1m6nIU',
    appId: '1:363823258532:android:fa9d901cebbbc543deff31',
    messagingSenderId: '363823258532',
    projectId: 'quest-demo-12845',
    storageBucket: 'quest-demo-12845.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBabGtXnm3pQxms3xWiqmVgnS6X2YDwhCQ',
    appId: '1:363823258532:ios:771ec6b261919dfddeff31',
    messagingSenderId: '363823258532',
    projectId: 'quest-demo-12845',
    storageBucket: 'quest-demo-12845.appspot.com',
    iosClientId: '363823258532-mplnfan5hl342fno6g7vqhjtnrbbq7n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.questDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBabGtXnm3pQxms3xWiqmVgnS6X2YDwhCQ',
    appId: '1:363823258532:ios:771ec6b261919dfddeff31',
    messagingSenderId: '363823258532',
    projectId: 'quest-demo-12845',
    storageBucket: 'quest-demo-12845.appspot.com',
    iosClientId: '363823258532-mplnfan5hl342fno6g7vqhjtnrbbq7n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.questDemo',
  );
}
